trigger:
  - master 

pr:
  - master

jobs:
  - job: TestsForGMSO
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to path

      - bash: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels omnia
          conda config --add channels janschulz
          conda config --add channels conda-forge
          conda config --add channels mosdef
        displayName: Add relavent channels

      - bash: |
          conda create -n test-environment
          source activate test-environment
          conda install --yes --file requirements-test.txt
          conda install pytest
          pip install -e .
        displayName: Install requirements, Install branch

      - bash: |
          source activate test-environment
          python -m pytest -v gmso/tests/ 
        displayName: Run Tests

      - bash: |
          source activate test-environment
          coverage xml
          codecov --file ./coverage.xml --token 4020cb2c-5787-485a-92f2-5d106dff85a1
          coverage html
        displayName: Upload Coverage Report
      
      - task: PublishCodeCoverageResults@1
        inputs: 
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
        displayName: Publish Coverage Report
